config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'datatables/datatables_alteditor'
  get 'datatables/datatables_autofill'
  get 'datatables/datatables_basic'
  get 'datatables/datatables_buttons'
  get 'datatables/datatables_colreorder'
  get 'datatables/datatables_columnfilter'
  get 'datatables/datatables_export'
  get 'datatables/datatables_fixedcolumns'
  get 'datatables/datatables_fixedheader'
  get 'datatables/datatables_keytable'
  get 'datatables/datatables_responsive'
  get 'datatables/datatables_responsive_alt'
  get 'datatables/datatables_rowgroup'
  get 'datatables/datatables_rowreorder'
  get 'datatables/datatables_scroller'
  get 'datatables/datatables_select'
  get 'docs/docs_buildnotes'
  get 'docs/docs_community_support'
  get 'docs/docs_flavors_editions'
  get 'docs/docs_general'
  get 'docs/docs_licensing'
  get 'docs/docs_premium_support'
  get 'docs/docs_project_structure'
  get 'form/form_basic_inputs'
  get 'form/form_checkbox_radio'
  get 'form/form_input_groups'
  get 'form/form_validation'
  get 'form_plugins/form_plugins_colorpicker'
  get 'form_plugins/form_plugins_datepicker'
  get 'form_plugins/form_plugins_daterange_picker'
  get 'form_plugins/form_plugins_dropzone'
  get 'form_plugins/form_plugins_imagecropper'
  get 'form_plugins/form_plugins_inputmask'
  get 'form_plugins/form_plugins_ionrangeslider'
  get 'form_plugins/form_plugins_markdown'
  get 'form_plugins/form_plugins_nouislider'
  get 'form_plugins/form_plugins_select2'
  get 'form_plugins/form_plugins_summernote'
  get 'form_plugins/form_plugins_wizard'
  get 'icons/icons_fontawesome_brand'
  get 'icons/icons_fontawesome_duotone'
  get 'icons/icons_fontawesome_light'
  get 'icons/icons_fontawesome_regular'
  get 'icons/icons_fontawesome_solid'
  get 'icons/icons_nextgen_base'
  get 'icons/icons_nextgen_general'
  get 'icons/icons_stack_generate'
  get 'icons/icons_stack_showcase'
  get 'icons/icons_webfonts_faq'
  get 'intel/intel_analytics_dashboard'
  get 'intel/intel_introduction'
  get 'intel/intel_marketing_dashboard'
  get 'intel/intel_privacy'
  get 'miscellaneous/miscellaneous_fullcalendar'
  get 'miscellaneous/miscellaneous_lightgallery'
  get 'miscellaneous/miscellaneous_treeview'
  get 'notifications/notifications_sweetalert2'
  get 'notifications/notifications_toastr'
  get 'page/page_chat'
  get 'page/page_confirmation'
  get 'page/page_contacts'
  get 'page/page_error'
  get 'page/page_error_404'
  get 'page/page_error_announced'
  get 'page/page_forget'
  get 'page/page_forum_discussion'
  get 'page/page_forum_list'
  get 'page/page_forum_threads'
  get 'page/page_inbox_general'
  get 'page/page_inbox_read'
  get 'page/page_inbox_write'
  get 'page/page_invoice'
  get 'page/page_locked'
  get 'page/page_login'
  get 'page/page_login_alt'
  get 'page/page_profile'
  get 'page/page_projects'
  get 'page/page_register'
  get 'page/page_search'
  get 'plugins/plugins_appcore'
  get 'plugins/plugins_bootbox'
  get 'plugins/plugins_faq'
  get 'plugins/plugins_i18next'
  get 'plugins/plugins_navigation'
  get 'plugins/plugins_pacejs'
  get 'plugins/plugins_slimscroll'
  get 'plugins/plugins_smartpanels'
  get 'plugins/plugins_throttle'
  get 'plugins/plugins_waves'
  get 'settings/settings_how_it_works'
  get 'settings/settings_layout_options'
  get 'settings/settings_saving_db'
  get 'settings/settings_skin_options'
  get 'settings/settings_theme_modes'
  get 'statistics/statistics_c3'
  get 'statistics/statistics_chartist'
  get 'statistics/statistics_chartjs'
  get 'statistics/statistics_dygraph'
  get 'statistics/statistics_easypiechart'
  get 'statistics/statistics_flot'
  get 'statistics/statistics_peity'
  get 'statistics/statistics_sparkline'
  get 'tables/tables_basic'
  get 'tables/tables_generate_style'
  get 'ui/ui_accordion'
  get 'ui/ui_alerts'
  get 'ui/ui_badges'
  get 'ui/ui_breadcrumbs'
  get 'ui/ui_button_group'
  get 'ui/ui_buttons'
  get 'ui/ui_cards'
  get 'ui/ui_carousel'
  get 'ui/ui_collapse'
  get 'ui/ui_dropdowns'
  get 'ui/ui_list_filter'
  get 'ui/ui_modal'
  get 'ui/ui_navbars'
  get 'ui/ui_pagination'
  get 'ui/ui_panels'
  get 'ui/ui_popovers'
  get 'ui/ui_progress_bars'
  get 'ui/ui_scrollspy'
  get 'ui/ui_side_panel'
  get 'ui/ui_spinners'
  get 'ui/ui_tabs_accordions'
  get 'ui/ui_tabs_pills'
  get 'ui/ui_toasts'
  get 'ui/ui_tooltips'
  get 'ui/ui_tooltips_popovers'
  get 'utilities/utilities_borders'
  get 'utilities/utilities_clearfix'
  get 'utilities/utilities_color_pallet'
  get 'utilities/utilities_display_property'
  get 'utilities/utilities_flexbox'
  get 'utilities/utilities_fonts'
  get 'utilities/utilities_helpers'
  get 'utilities/utilities_position'
  get 'utilities/utilities_responsive_grid'
  get 'utilities/utilities_sizing'
  get 'utilities/utilities_spacing'
  get 'utilities/utilities_typography'
  get 'welcome/blank'
end

app/controllers/utilities_controller.rb
class UtilitiesController < ApplicationController
end

app/views/utilities/utilities_borders.html.erb
<%
  content_for(:title, 'Borders')
  content_for(:category_1, 'Utilities')
%>

<% content_for :heading do %>
  Borders
<% end %>

<% content_for :pagedescription do %>
  Use border utilities to quickly style the border and border-radius of an element. Great for images, buttons, or any other element.
<% end %>

<div class="row">
    <div class="col-xl-6">
    	<!--Colorful borders-->
		<div id="panel-1" class="panel">
			<div class="panel-hdr">	
				<h2>
					Colorful <span class="fw-300"><i>borders</i></span> 
				</h2>
				<div class="panel-toolbar">
					<button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
					<button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
					<button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
				</div>
			</div>
			<div class="panel-container show">
				<div class="panel-content">									
					<div class="panel-tag">
						Use color profiles to the following border colors <code>,border-primary</code>, <code>.border-secondary</code>, <code>.border-success</code>, <code>.border-danger</code>, <code>.border-warning</code>, <code>.border-info</code>, <code>.border-light</code>, <code>.border-dark</code>, <code>.border-white</code>, <code>.border-transparent</code>, <code>.border-faded</code>
					</div>
					<div class="demo">
						<div class="border border-primary width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border border-secondary width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border border-success width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border border-danger width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border border-warning width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border border-info width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border border-light width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border border-dark width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border border-white width-10 height-10 d-inline-block bg-faded"></div>
					</div>
				</div>
			</div>
		</div>    	
		<!--Add borders-->
		<div id="panel-2" class="panel">
			<div class="panel-hdr">	
				<h2>
					Add <span class="fw-300"><i>borders</i></span> 
				</h2>
				<div class="panel-toolbar">
					<button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
					<button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
					<button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
				</div>
			</div>
			<div class="panel-container show">
				<div class="panel-content">									
					<div class="panel-tag">
						Add border using <code>.border</code>, <code>.border-top</code>, <code>.border-right</code>, <code>.border-right</code>, <code>.border-bottom</code>, <code>.border-left</code>
					</div>
					<div class="demo">
						<div class="border width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border-top width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border-right width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border-bottom width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border-left width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border rounded-circle width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border rounded width-10 height-10 d-inline-block bg-faded"></div>
					</div>
				</div>
			</div>
		</div>			
	</div>
	<div class="col-xl-6">	
		<!--Rounded-->
		<div id="panel-3" class="panel">
			<div class="panel-hdr">	
				<h2>
					Rounded <span class="fw-300"><i>example</i></span> 
				</h2>
				<div class="panel-toolbar">
					<button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
					<button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
					<button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
				</div>
			</div>
			<div class="panel-container show">
				<div class="panel-content">									
					<div class="panel-tag">
						Round edges or control each corner using <code>.rounded</code>, <code>rounded-top</code>, <code>rounded-right</code>, <code>rounded-bottom</code>, <code>rounded-left</code>, <code>rounded-circle</code>, <code>rounded-0</code>, <code>.rounded-plus</code>, <code>.rounded-{sm,lg}</code>, <code>.rounded-pill</code>, <code>border-{top,bottom}-{left,right}-radius-0</code>
					</div>
					<div class="demo">				
						<div class="rounded bg-fusion-50 width-10 height-10 d-inline-block bg-faded"></div>
						<div class="rounded-top bg-fusion-50 width-10 height-10 d-inline-block bg-faded"></div>
						<div class="rounded-right bg-fusion-50 width-10 height-10 d-inline-block bg-faded"></div>
						<div class="rounded-bottom bg-fusion-50 width-10 height-10 d-inline-block bg-faded"></div>
						<div class="rounded-left bg-fusion-50 width-10 height-10 d-inline-block bg-faded"></div>
						<div class="rounded-circle bg-fusion-50 width-10 height-10 d-inline-block bg-faded"></div>
						<div class="rounded-plus bg-fusion-50 width-10 height-10 d-inline-block bg-faded"></div>
						<div class="rounded-0 bg-fusion-50 width-10 height-10 d-inline-block bg-faded"></div>
					</div>
				</div>
			</div>
		</div>		
		<!--Remove borders-->
		<div id="panel-4" class="panel">
			<div class="panel-hdr">	
				<h2>
					Remove <span class="fw-300"><i>borders</i></span> 
				</h2>
				<div class="panel-toolbar">
					<button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
					<button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
					<button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
				</div>
			</div>
			<div class="panel-container show">
				<div class="panel-content">									
					<div class="panel-tag">
						Subtract borders with <code>border-0</code>, <code>border-top-0</code>, <code>border-right-0</code>, <code>border-bottom-0</code>, <code>border-left-0</code>, <code>.border-transparent</code>
					</div>
					<div class="demo">
						<div class="border-0 width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border border-top-0 width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border border-right-0 width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border border-bottom-0 width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border border-left-0 width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border rounded-circle border-right-0 border-left-0 width-10 height-10 d-inline-block bg-faded"></div>
						<div class="border rounded width-10 border-right-0 border-left-0 height-10 d-inline-block bg-faded"></div>
					</div>
				</div>
			</div>
		</div>		
	</div>
</div>

app/views/utilities/utilities_clearfix.html.erb
<%
  content_for(:title, 'Clearfix')
  content_for(:category_1, 'Utilities')
%>

<% content_for :heading do %>
  <i class='subheader-icon fal fa-window'></i>  Clearfix
<% end %>

<% content_for :pagedescription do %>
  Quickly and easily clear floated content within a container by adding a clearfix utility.
<% end %>

<% content_for :head_block do %>
  <%= stylesheet_link_tag 'smartadmin/theme-demo', media: 'screen, print' %>
<% end %>

<div class="row">
	<div class="col-xl-12">
		<div id="panel-1" class="panel">
			<div class="panel-hdr">	
				<h2>
					Clearfix <span class="fw-300"><i>example</i></span> 
				</h2>
				<div class="panel-toolbar">
					<button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
					<button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
					<button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
				</div>
			</div>
			<div class="panel-container show">
				<div class="panel-content">									
					<div class="panel-tag">
						Easily clear <code>float</code>s by adding <code>.clearfix</code> <strong>to the parent element</strong>. Can also be used as a mixin.
					</div>
					<div class="bg-info clearfix">
						<button type="button" class="btn btn-secondary float-left">Example Button floated left</button>
						<button type="button" class="btn btn-secondary float-right">Example Button floated right</button>
					</div>
				</div>
			</div>
		</div>	
	</div>
</div>

app/views/utilities/utilities_display_property.html.erb
<%
  content_for(:title, 'Display Property')
  content_for(:category_1, 'Utilities')
%>

<% content_for :heading do %>
  <i class='subheader-icon fal fa-window'></i>  Display Property
<% end %>

<% content_for :pagedescription do %>
  Quickly and responsively toggle the display value of components and more with our display utilities.
<% end %>

<% content_for :head_block do %>
  <%= stylesheet_link_tag 'smartadmin/theme-demo', media: 'screen, print' %>
<% end %>

<div class="alert alert-primary alert-dismissible">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
	<span aria-hidden="true">
	<i class="<%= Rails.configuration.icon_prefix %> fa-times"></i>
	</span>
	</button>
	<div class="d-flex flex-start w-100">
		<div class="mr-2 d-sm-none d-md-block">
			<span class="icon-stack icon-stack-lg">
			<i class="base base-6 icon-stack-3x opacity-100 color-primary-500"></i>
			<i class="base base-10 icon-stack-2x opacity-100 color-primary-300 fa-flip-vertical"></i>
			<i class="<%= Rails.configuration.icon_prefix %> fa-info icon-stack-1x opacity-100 color-white"></i>
			</span>
		</div>
		<div class="d-flex flex-fill">
			<div class="flex-fill">
				<span class="h5">How it works</span>
				<br> Change the value of the display property with our responsive display utility classes. We purposely support only a subset of all possible values for display. Classes can be combined for various effects as you need.
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xl-6">
		<div id="panel-1" class="panel">
			<div class="panel-hdr">	
				<h2>
					Displaying <span class="fw-300"><i>elements</i></span> 
				</h2>
				<div class="panel-toolbar">
					<button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
					<button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
					<button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
				</div>
			</div>
			<div class="panel-container show">
				<div class="panel-content">									
					<div class="panel-tag">
						Display utility classes that apply to all <%= link_to 'breakpoints', utilities_utilities_responsive_grid_path, target: '_blank' %>, from <code>xs</code> to <code>xl</code>, have no breakpoint abbreviation in them. This is because those classes are applied from <code>min-width: 0;</code> and up, and thus are not bound by a media query. The remaining breakpoints, however, do include a breakpoint abbreviation
					</div>
					<p>As such, the classes are named using the format:</p>
					<ul class="list-spaced">
						<li><code>.d-{value}</code> for <code>xs</code></li>
						<li><code>.d-{breakpoint}-{value}</code> for <code>sm</code>, <code>md</code>, <code>lg</code>, and <code>xl</code>.</li>
					</ul>
					<p>Where <em>value</em> is one of:</p>
					<ul class="list-spaced">
						<li><code>none</code></li>
						<li><code>inline</code></li>
						<li><code>inline-block</code></li>
						<li><code>block</code></li>
						<li><code>table</code></li>
						<li><code>table-cell</code></li>
						<li><code>table-row</code></li>
						<li><code>flex</code></li>
						<li><code>inline-flex</code></li>
					</ul>
					<p>The media queries effect screen widths with the given breakpoint <em>or larger</em>. For example, <code>.d-lg-none</code> sets <code>display: none;</code> on both <code>lg</code> and <code>xl</code> screens.</p>
				</div>
			</div>
		</div>
		<div id="panel-2" class="panel">
			<div class="panel-hdr">	
				<h2>
					Hiding <span class="fw-300"><i>elements (BS3 method)</i></span> 
				</h2>
				<div class="panel-toolbar">
					<button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
					<button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
					<button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
				</div>
			</div>
			<div class="panel-container show">
				<div class="panel-content">									
					<div class="panel-tag">
						This method for hidding elements is from Bootstrap version 3.0, it is a more quicker way of hiding responsive elements. However, the Bootstrap 4 method will give you greater control. <strong>Remember to use either of the method on a single element, otherwise it may not work</strong>
					</div>
					<div class="table-responsive">
						<table class="table table-bordered">
							<thead>
								<tr>
									<th scope="col" class="border-top-0" style="width: 150px"></th>
									<th scope="col">
										Extra small devices
										<small class="d-block fs-sm text-muted">
											Phones (&lt;0px)
										</small>
									</th>
									<th scope="col">
										Small devices
										<small class="d-block fs-sm text-muted">
											Tablets (≥576px)
										</small>
									</th>
									<th scope="col">
										Medium devices
										<small class="d-block fs-sm text-muted">
											Desktops (≥768px)
										</small>
									</th>
									<th scope="col">
										Large devices
										<small class="d-block fs-sm text-muted">
											Desktops (≥992px)
										</small>
									</th>
									<th scope="col">
										Extra Large devices
										<small class="d-block fs-sm text-muted">
											Desktops (≥1200px)
										</small>
									</th>
								</tr>
							</thead>					
							<tbody>
								<tr>
									<th scope="row"><code>.hidden-xs-down</code></th>
									<td class="text-danger">hidden</td>
									<td class="text-success">visible</td>
									<td class="text-success">visible</td>
									<td class="text-success">visible</td>
									<td class="text-success">visible</td>
								</tr>
								<tr>
									<th scope="row"><code>.hidden-sm-down</code></th>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
									<td class="text-success">visible</td>
									<td class="text-success">visible</td>
									<td class="text-success">visible</td>
								</tr>
								<tr>
									<th scope="row"><code>.hidden-md-down</code></th>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
									<td class="text-success">visible</td>
									<td class="text-success">visible</td>
								</tr>
								<tr>
									<th scope="row"><code>.hidden-lg-down</code></th>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
									<td class="text-success">visible</td>
								</tr>
								<tr>
									<th scope="row"><code>.hidden-xl-down</code></th>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
								</tr>
								<tr>
									<th scope="row"><code>.hidden-xs-up</code></th>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
								</tr>
								<tr>
									<th scope="row"><code>.hidden-sm-up</code></th>
									<td class="text-success">visible</td>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
								</tr>
								<tr>
									<th scope="row"><code>.hidden-md-up</code></th>
									<td class="text-success">visible</td>
									<td class="text-success">visible</td>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
								</tr>
								<tr>
									<th scope="row"><code>.hidden-lg-up</code></th>
									<td class="text-success">visible</td>
									<td class="text-success">visible</td>
									<td class="text-success">visible</td>
									<td class="text-danger">hidden</td>
									<td class="text-danger">hidden</td>
								</tr>
								<tr>
									<th scope="row"><code>.hidden-xl-up</code></th>
									<td class="text-success">visible</td>
									<td class="text-success">visible</td>
									<td class="text-success">visible</td>
									<td class="text-success">visible</td>
									<td class="text-danger">hidden</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xl-6">
		<div id="panel-3" class="panel">
			<div class="panel-hdr">	
				<h2>
					Display  <span class="fw-300"><i>Print</i></span> 
				</h2>
				<div class="panel-toolbar">
					<button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
					<button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
					<button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
				</div>
			</div>
			<div class="panel-container show">
				<div class="panel-content">									
					<p>
						Change the <code>display</code> value of elements when printing with our print display utility classes. Includes support for the same <code>display</code> values as our responsive <code>.d-*</code> utilities.
					</p>
					<ul class="list-spaced">
						<li><code>.d-print-none</code></li>
						<li><code>.d-print-inline</code></li>
						<li><code>.d-print-inline-block</code></li>
						<li><code>.d-print-block</code></li>
						<li><code>.d-print-table</code></li>
						<li><code>.d-print-table-row</code></li>
						<li><code>.d-print-table-cell</code></li>
						<li><code>.d-print-flex</code></li>
						<li><code>.d-print-inline-flex</code></li>
					</ul>
					<p>The print and display classes can be combined.</p>
				</div>
			</div>
		</div>
		<div id="panel-4" class="panel">
			<div class="panel-hdr">	
				<h2>
					Hiding <span class="fw-300"><i>elements (BS4 method)</i></span> 
				</h2>
				<div class="panel-toolbar">
					<button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
					<button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
					<button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
				</div>
			</div>
			<div class="panel-container show">
				<div class="panel-content">									
					<div class="panel-tag">
						<p>For faster mobile-friendly development, use responsive display classes for showing and hiding elements by device. Avoid creating entirely different versions of the same site, instead hide elements responsively for each screen size.</p>

						<p>To hide elements simply use the <code>.d-none</code> class or one of the <code>.d-{sm,md,lg,xl}-none</code> classes for any responsive screen variation.</p>

						<p>To show an element only on a given interval of screen sizes you can combine one <code>.d-*-none</code> class with a <code>.d-*-*</code> class, for example <code>.d-none .d-md-block .d-xl-none</code> will hide the element for all screen sizes except on medium and large devices.</p>
					</div>
					<table class="table table-bordered">
						<thead>
							<tr>
								<th>Screen Size</th>
								<th>Class</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Hidden on all</td>
								<td><code>.d-none</code></td>
							</tr>
							<tr>
								<td>Hidden only on xs</td>
								<td><code>.d-none .d-sm-block</code></td>
							</tr>
							<tr>
								<td>Hidden only on sm</td>
								<td><code>.d-sm-none .d-md-block</code></td>
							</tr>
							<tr>
								<td>Hidden only on md</td>
								<td><code>.d-md-none .d-lg-block</code></td>
							</tr>
							<tr>
								<td>Hidden only on lg</td>
								<td><code>.d-lg-none .d-xl-block</code></td>
							</tr>
							<tr>
								<td>Hidden only on xl</td>
								<td><code>.d-xl-none</code></td>
							</tr>
							<tr>
								<td>Visible on all</td>
								<td><code>.d-block</code></td>
							</tr>
							<tr>
								<td>Visible only on xs</td>
								<td><code>.d-block .d-sm-none</code></td>
							</tr>
							<tr>
								<td>Visible only on sm</td>
								<td><code>.d-none .d-sm-block .d-md-none</code></td>
							</tr>
							<tr>
								<td>Visible only on md</td>
								<td><code>.d-none .d-md-block .d-lg-none</code></td>
							</tr>
							<tr>
								<td>Visible only on lg</td>
								<td><code>.d-none .d-lg-block .d-xl-none</code></td>
							</tr>
							<tr>
								<td>Visible only on xl</td>
								<td><code>.d-none .d-xl-block</code></td>
							</tr>
						</tbody>
					</table>

				</div>
			</div>
		</div>
	</div>
</div>