config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'datatables/datatables_alteditor'
  get 'datatables/datatables_autofill'
  get 'datatables/datatables_basic'
  get 'datatables/datatables_buttons'
  get 'datatables/datatables_colreorder'
  get 'datatables/datatables_columnfilter'
  get 'datatables/datatables_export'
  get 'datatables/datatables_fixedcolumns'
  get 'datatables/datatables_fixedheader'
  get 'datatables/datatables_keytable'
  get 'datatables/datatables_responsive'
  get 'datatables/datatables_responsive_alt'
  get 'datatables/datatables_rowgroup'
  get 'datatables/datatables_rowreorder'
  get 'datatables/datatables_scroller'
  get 'datatables/datatables_select'
  get 'docs/docs_buildnotes'
  get 'docs/docs_community_support'
  get 'docs/docs_flavors_editions'
  get 'docs/docs_general'
  get 'docs/docs_licensing'
  get 'docs/docs_premium_support'
  get 'docs/docs_project_structure'
  get 'form/form_basic_inputs'
  get 'form/form_checkbox_radio'
  get 'form/form_input_groups'
  get 'form/form_validation'
  get 'form_plugins/form_plugins_colorpicker'
  get 'form_plugins/form_plugins_datepicker'
  get 'form_plugins/form_plugins_daterange_picker'
  get 'form_plugins/form_plugins_dropzone'
  get 'form_plugins/form_plugins_imagecropper'
  get 'form_plugins/form_plugins_inputmask'
  get 'form_plugins/form_plugins_ionrangeslider'
  get 'form_plugins/form_plugins_markdown'
  get 'form_plugins/form_plugins_nouislider'
  get 'form_plugins/form_plugins_select2'
  get 'form_plugins/form_plugins_summernote'
  get 'form_plugins/form_plugins_wizard'
  get 'icons/icons_fontawesome_brand'
  get 'icons/icons_fontawesome_duotone'
  get 'icons/icons_fontawesome_light'
  get 'icons/icons_fontawesome_regular'
  get 'icons/icons_fontawesome_solid'
  get 'icons/icons_nextgen_base'
  get 'icons/icons_nextgen_general'
  get 'icons/icons_stack_generate'
  get 'icons/icons_stack_showcase'
  get 'icons/icons_webfonts_faq'
  get 'intel/intel_analytics_dashboard'
  get 'intel/intel_introduction'
  get 'intel/intel_marketing_dashboard'
  get 'intel/intel_privacy'
  get 'miscellaneous/miscellaneous_fullcalendar'
  get 'miscellaneous/miscellaneous_lightgallery'
  get 'miscellaneous/miscellaneous_treeview'
  get 'notifications/notifications_sweetalert2'
  get 'notifications/notifications_toastr'
  get 'page/page_chat'
  get 'page/page_confirmation'
  get 'page/page_contacts'
  get 'page/page_error'
  get 'page/page_error_404'
  get 'page/page_error_announced'
  get 'page/page_forget'
  get 'page/page_forum_discussion'
  get 'page/page_forum_list'
  get 'page/page_forum_threads'
  get 'page/page_inbox_general'
  get 'page/page_inbox_read'
  get 'page/page_inbox_write'
  get 'page/page_invoice'
  get 'page/page_locked'
  get 'page/page_login'
  get 'page/page_login_alt'
  get 'page/page_profile'
  get 'page/page_projects'
  get 'page/page_register'
  get 'page/page_search'
  get 'plugins/plugins_appcore'
  get 'plugins/plugins_bootbox'
  get 'plugins/plugins_faq'
  get 'plugins/plugins_i18next'
  get 'plugins/plugins_navigation'
  get 'plugins/plugins_pacejs'
  get 'plugins/plugins_slimscroll'
  get 'plugins/plugins_smartpanels'
  get 'plugins/plugins_throttle'
  get 'plugins/plugins_waves'
  get 'settings/settings_how_it_works'
  get 'settings/settings_layout_options'
  get 'settings/settings_saving_db'
  get 'settings/settings_skin_options'
  get 'settings/settings_theme_modes'
  get 'statistics/statistics_c3'
  get 'statistics/statistics_chartist'
  get 'statistics/statistics_chartjs'
  get 'statistics/statistics_dygraph'
  get 'statistics/statistics_easypiechart'
  get 'statistics/statistics_flot'
  get 'statistics/statistics_peity'
  get 'statistics/statistics_sparkline'
  get 'tables/tables_basic'
  get 'tables/tables_generate_style'
  get 'ui/ui_accordion'
  get 'ui/ui_alerts'
  get 'ui/ui_badges'
  get 'ui/ui_breadcrumbs'
  get 'ui/ui_button_group'
  get 'ui/ui_buttons'
  get 'ui/ui_cards'
  get 'ui/ui_carousel'
  get 'ui/ui_collapse'
  get 'ui/ui_dropdowns'
  get 'ui/ui_list_filter'
  get 'ui/ui_modal'
  get 'ui/ui_navbars'
  get 'ui/ui_pagination'
  get 'ui/ui_panels'
  get 'ui/ui_popovers'
  get 'ui/ui_progress_bars'
  get 'ui/ui_scrollspy'
  get 'ui/ui_side_panel'
  get 'ui/ui_spinners'
  get 'ui/ui_tabs_accordions'
  get 'ui/ui_tabs_pills'
  get 'ui/ui_toasts'
  get 'ui/ui_tooltips'
  get 'ui/ui_tooltips_popovers'
  get 'utilities/utilities_borders'
  get 'utilities/utilities_clearfix'
  get 'utilities/utilities_color_pallet'
  get 'utilities/utilities_display_property'
  get 'utilities/utilities_flexbox'
  get 'utilities/utilities_fonts'
  get 'utilities/utilities_helpers'
  get 'utilities/utilities_position'
  get 'utilities/utilities_responsive_grid'
  get 'utilities/utilities_sizing'
  get 'utilities/utilities_spacing'
  get 'utilities/utilities_typography'
  get 'welcome/blank'
end

app/views/shared/_blank_left_panel.html.erb
<% if Rails.configuration.app_sidebar %>
<!-- BEGIN Left Aside -->
<aside class="page-sidebar">

	<%= render 'shared/logo' %>

	<!-- BEGIN PRIMARY NAVIGATION -->
	<nav id="js-primary-nav" class="primary-nav" role="navigation">

		<%= render 'shared/nav_filter' %>
		<%= render 'shared/nav_info_card' %>	
		<%= render 'shared/blank_nav' %>
		<%= render 'shared/nav_filter_msg' %>
	</nav>
	<!-- END PRIMARY NAVIGATION -->

	<!-- NAV FOOTER -->
	<%= render 'shared/nav_footer' %>
	<!-- END NAV FOOTER -->

</aside>
<!-- END Left Aside -->
<% end %>

app/views/shared/_blank_nav.html.erb
<!-- 
TIP: The menu items are not auto translated. You must have a residing lang file associated with the menu saved inside dist/media/data with reference to each 'data-i18n' attribute.
-->
<ul id="js-nav-menu" class="nav-menu">
	<li <%= yield(:#is pagename "in" "blankpage") %>class="active" >
		<%= link_to welcome_blank_path, title: 'Blank Project" data-filter-tags="blank page' do %>
  <i class="<%= Rails.configuration.icon_prefix %> fa-globe"></i>
			<span class="nav-link-text" data-i18n="nav.blankpage">Blank Project</span>
<% end %>
	</li>
	<li class="nav-title">Navigation Title</li>
	<li <%= yield(:#is pagename "in" "category menu child sublevel item") %>class="active open" >
		<a href="#" title="Category" data-filter-tags="category">
			<i class="<%= Rails.configuration.icon_prefix %> fa-file"></i>
			<span class="nav-link-text" data-i18n="nav.category">Category</span>
		</a>
		<ul>
			<li <%= yield(:#is pagename "in" "") %>class="active open" >
				<a href="javascript:void(0);" title="Menu child" data-filter-tags="utilities menu child">
					<span class="nav-link-text" data-i18n="nav.utilities_menu_child">Sub-category</span>
				</a>
				<ul>
					<li <%= yield(:#is pagename "===" "javascript:void(0);") %>class="active" >
						<a href="javascript:void(0);" title="Sublevel Item" data-filter-tags="utilities menu child sublevel item">
							<span class="nav-link-text" data-i18n="nav.utilities_menu_child_sublevel_item">Sublevel Item</span>
						</a>
					</li>
					<li <%= yield(:#is pagename "===" "javascript:void(0);") %>class="active" >
						<a href="javascript:void(0);" title="Another Item" data-filter-tags="utilities menu child another item">
							<span class="nav-link-text" data-i18n="nav.utilities_menu_child_another_item">Another Item</span>
						</a>
					</li>
				</ul>
			</li>
			<li class="disabled">
				<a href="javascript:void(0);" title="Disabled item" data-filter-tags="utilities disabled item">
					<span class="nav-link-text" data-i18n="nav.utilities_disabled_item">Disabled item</span>
				</a>
			</li>
		</ul>
	</li>
	<!-- Example of open and active states -->
	<li class="active open">
		<a href="#" title="Category" data-filter-tags="category">
			<i class="<%= Rails.configuration.icon_prefix %> fa-plus"></i>
			<span class="nav-link-text" data-i18n="nav.category">Open Item</span>
		</a>
		<ul>
			<li class="active open">
				<a href="javascript:void(0);" title="Menu child" data-filter-tags="utilities menu child">
					<span class="nav-link-text" data-i18n="nav.utilities_menu_child">Open Sub-category</span>
				</a>
				<ul>
					<li class="active">
						<a href="javascript:void(0);" title="Sublevel Item" data-filter-tags="utilities menu child sublevel item">
							<span class="nav-link-text" data-i18n="nav.utilities_menu_child_sublevel_item">Active Item</span>
						</a>
					</li>
				</ul>
			</li>
		</ul>
	</li>
</ul>

app/views/shared/_chat_contact.html.erb
<div id="js-chat-contact" class="flex-wrap position-relative slide-on-mobile slide-on-mobile-left border-faded border-left-0 border-top-0 border-bottom-0">
	<!-- BEGIN msgr-list -->
	<div class="d-flex flex-column bg-faded position-absolute pos-top pos-bottom w-100">
		<div class="px-3 py-4">
			<input type="text" class="form-control bg-white" placeholder="Search key words">
		</div>
		<div class="flex-1 h-100 custom-scrollbar">
			<div class="w-100">
				<div class="nav-title m-0 px-3 text-muted">Chat History</div>
				<ul class="list-unstyled m-0">
					<li>
						<div class="d-flex w-100 px-3 py-2 text-dark hover-white cursor-pointer show-child-on-hover">
							<div class="profile-image-md rounded-circle" style="background-image: url('<%= image_path 'smartadmin/demo/avatars/avatar-d.png' %>'); background-size: cover;"></div>
							<div class="px-2 flex-1">
								<div class="text-truncate text-truncate-md">
									Tracey Chang
									<small class="d-block text-muted text-truncate text-truncate-md">
										2020-01-31 
									</small>
								</div>
							</div>
							<div class="position-absolute pos-right mt-2 mr-3 show-on-hover-parent">
								<button class="btn btn-danger btn-xs btn-icon rounded-circle shadow-0" data-toggle="tooltip" data-template="<div class=&quot;tooltip&quot; role=&quot;tooltip&quot;><div class=&quot;tooltip-inner bg-danger-500&quot;></div></div>" data-original-title="Delete">
									<i class="<%= Rails.configuration.icon_prefix %> fa-trash-alt"></i>
								</button>
							</div>
						</div>
					</li>
					<li>
						<div class="d-flex w-100 px-3 py-2 text-dark hover-white cursor-pointer show-child-on-hover">
							<div class="profile-image-md rounded-circle" style="background-image: url('<%= image_path 'smartadmin/demo/avatars/avatar-b.png' %>'); background-size: cover;"></div>
							<div class="px-2 flex-1">
								<div class="text-truncate text-truncate-md">
									Oliver Kopyuv
									<small class="d-block text-muted text-truncate text-truncate-md">
										2019-03-15 
									</small>
								</div>
							</div>
							<div class="position-absolute pos-right mt-2 mr-3 show-on-hover-parent">
								<button class="btn btn-danger btn-xs btn-icon rounded-circle shadow-0" data-toggle="tooltip" data-template="<div class=&quot;tooltip&quot; role=&quot;tooltip&quot;><div class=&quot;tooltip-inner bg-danger-500&quot;></div></div>" data-original-title="Delete">
									<i class="<%= Rails.configuration.icon_prefix %> fa-trash-alt"></i>
								</button>
							</div>
						</div>
					</li>
					<li>
						<div class="d-flex w-100 px-3 py-2 text-dark hover-white cursor-pointer show-child-on-hover">
							<div class="profile-image-md rounded-circle" style="background-image: url('<%= image_path 'smartadmin/demo/avatars/avatar-e.png' %>'); background-size: cover;"></div>
							<div class="px-2 flex-1">
								<div class="text-truncate text-truncate-md">
									Dr. John Cook PhD
									<small class="d-block text-muted text-truncate text-truncate-md">
										2023-05-27 
									</small>
								</div>
							</div>
							<div class="position-absolute pos-right mt-2 mr-3 show-on-hover-parent">
								<button class="btn btn-danger btn-xs btn-icon rounded-circle shadow-0" data-toggle="tooltip" data-template="<div class=&quot;tooltip&quot; role=&quot;tooltip&quot;><div class=&quot;tooltip-inner bg-danger-500&quot;></div></div>" data-original-title="Delete">
									<i class="<%= Rails.configuration.icon_prefix %> fa-trash-alt"></i>
								</button>
							</div>
						</div>				
					</li>
					<li>
						<div class="d-flex w-100 px-3 py-2 text-dark hover-white cursor-pointer show-child-on-hover">
							<div class="profile-image-md rounded-circle" style="background-image: url('<%= image_path 'smartadmin/demo/avatars/avatar-g.png' %>'); background-size: cover;"></div>
							<div class="px-2 flex-1">
								<div class="text-truncate text-truncate-md">
									Ali Amdaney
									<small class="d-block text-muted text-truncate text-truncate-md">
										2023-06-11 
									</small>
								</div>
							</div>
							<div class="position-absolute pos-right mt-2 mr-3 show-on-hover-parent">
								<button class="btn btn-danger btn-xs btn-icon rounded-circle shadow-0" data-toggle="tooltip" data-template="<div class=&quot;tooltip&quot; role=&quot;tooltip&quot;><div class=&quot;tooltip-inner bg-danger-500&quot;></div></div>" data-original-title="Delete">
									<i class="<%= Rails.configuration.icon_prefix %> fa-trash-alt"></i>
								</button>
							</div>
						</div>
					</li>
				</ul>

				<div class="nav-title px-3 text-muted">Missed calls</div>

				<ul class="list-unstyled m-0">
					<li>
						<div class="d-flex w-100 px-3 py-2 text-dark hover-white cursor-pointer show-child-on-hover">
							<div class="profile-image-md rounded-circle" style="background-image: url('<%= image_path 'smartadmin/demo/avatars/avatar-m.png' %>'); background-size: cover;"></div>
							<div class="px-2 flex-1">
								<div class="text-truncate text-truncate-md">
									+714651347790
									<small class="d-block font-italic fs-xs opacity-50">
										Missed Call 
									</small>
								</div>
							</div>
							<div class="position-absolute pos-right mt-2 mr-3 show-on-hover-parent">
								<button class="btn btn-success btn-xs btn-icon rounded-circle shadow-0" data-toggle="tooltip" data-template="<div class=&quot;tooltip&quot; role=&quot;tooltip&quot;><div class=&quot;tooltip-inner bg-success-500&quot;></div></div>" data-original-title="Play voicemail">
									<i class="<%= Rails.configuration.icon_prefix %> fa-play"></i>
								</button>
								<button class="btn btn-info btn-xs btn-icon rounded-circle shadow-0" data-toggle="tooltip" data-template="<div class=&quot;tooltip&quot; role=&quot;tooltip&quot;><div class=&quot;tooltip-inner bg-info-500&quot;></div></div>" data-original-title="Call back">
									<i class="<%= Rails.configuration.icon_prefix %> fa-phone"></i>
								</button>
							</div>
						</div>
					</li>
					<li>
						<div class="d-flex w-100 px-3 py-2 text-dark hover-white cursor-pointer show-child-on-hover">
							<div class="profile-image-md rounded-circle" style="background-image: url('<%= image_path 'smartadmin/demo/avatars/avatar-m.png' %>'); background-size: cover;"></div>
							<div class="px-2 flex-1">
								<div class="text-truncate text-truncate-md">
									+13471349199
									<small class="d-block font-italic fs-xs opacity-50">
										Ended in 32 minutes
									</small>
								</div>
							</div>
							<div class="position-absolute pos-right mt-2 mr-3 show-on-hover-parent">
								<button class="btn btn-info btn-xs btn-icon rounded-circle shadow-0" data-toggle="tooltip" data-template="<div class=&quot;tooltip&quot; role=&quot;tooltip&quot;><div class=&quot;tooltip-inner bg-info-500&quot;></div></div>" data-original-title="Call back">
									<i class="<%= Rails.configuration.icon_prefix %> fa-phone"></i>
								</button>
							</div>
						</div>
					</li>
				</ul>
	
			</div>
		</div>
	</div>
	<!-- END msgr-list -->
</div>

<div class="slide-backdrop" data-action="toggle" data-class="slide-on-mobile-left-show" data-target="#js-chat-contact"></div>

app/views/shared/_copyright_header.html.erb
<!-- 
Template Name:  SmartAdmin Ruby on Rails Edition - Template built with Bootstrap 4 and Ruby on Rails 6
Version: <%= Rails.configuration.version %>
Author: Sunnyat A.
Website: https://smartadmin-rails-full.herokuapp.com/
Purchase: https://wrapbootstrap.com/theme/smartadmin-ruby-on-rails-edition-WB0H2M263
License: You must have a valid license purchased only from wrapbootstrap.com (link above) in order to legally use this theme for your project.
-->

app/views/shared/_dropdown_menu.html.erb
<div class="dropdown-header bg-trans-gradient d-flex flex-row py-4 rounded-top">
	<div class="d-flex flex-row align-items-center mt-1 mb-1 color-white">
		<span class="mr-2">
			<%= image_tag "smartadmin/demo/avatars/#{Rails.configuration.avatar}", class: 'rounded-circle profile-image', alt: Rails.configuration.user %>
		</span>
		<div class="info-card-text">
			<div class="fs-lg text-truncate text-truncate-lg"><%= Rails.configuration.user %></div>
			<span class="text-truncate text-truncate-md opacity-80"><%= Rails.configuration.email %></span>
		</div>
	</div>
</div>
<div class="dropdown-divider m-0"></div>
<a href="#" class="dropdown-item" data-action="app-reset">
	<span data-i18n="drpdwn.reset_layout">Reset Layout</span>
</a>
<a href="#" class="dropdown-item" data-toggle="modal" data-target=".js-modal-settings">
	<span data-i18n="drpdwn.settings">Settings</span>
</a>
<div class="dropdown-divider m-0"></div>

<a href="#" class="dropdown-item" data-action="app-fullscreen">
	<span data-i18n="drpdwn.fullscreen">Fullscreen</span> 
	<i class="float-right text-muted fw-n">F11</i>
</a>
<a href="#" class="dropdown-item" data-action="app-print">
	<span data-i18n="drpdwn.print">Print</span> 
	<i class="float-right text-muted fw-n">Ctrl + P</i>
</a>
<div class="dropdown-multilevel dropdown-multilevel-left">
	<div class="dropdown-item">
		Language
	</div>
	<div class="dropdown-menu">
		<a href="#?lang=fr" class="dropdown-item" data-action="lang" data-lang="fr">Français</a>
		<a href="#?lang=en" class="dropdown-item active" data-action="lang" data-lang="en">English (US)</a>
		<a href="#?lang=es" class="dropdown-item" data-action="lang" data-lang="es">Español</a>
		<a href="#?lang=ru" class="dropdown-item" data-action="lang" data-lang="ru">Русский язык</a>
		<a href="#?lang=jp" class="dropdown-item" data-action="lang" data-lang="jp">日本語</a>
		<a href="#?lang=ch" class="dropdown-item" data-action="lang" data-lang="ch">中文</a>
	</div>
</div>
<div class="dropdown-divider m-0"></div>
<%= link_to page_page_login_path, class: 'dropdown-item fw-500 pt-3 pb-3' do %>
  <span data-i18n="drpdwn.page-logout">Logout</span> 
	<span class="float-right fw-n">&commat;<%= Rails.configuration.twitter %></span>
<% end %>

app/views/shared/_head.html.erb
<meta charset="utf-8">

<title>
<% if content_for?(:title) %>
	<%= yield :title %> - <%= yield :category_1 %> - <%= Rails.configuration.app %> v<%= Rails.configuration.version %>
<% else %>
	<%= Rails.configuration.app %>
<% end %>
</title>

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= javascript_pack_tag 'application' %>

<meta name="description" content="<%= yield :title %>">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no, minimal-ui">
<!-- Call App Mode on ios devices -->
<meta name="apple-mobile-web-app-capable" content="yes" />
<!-- Remove Tap Highlight on Windows Phone IE -->
<meta name="msapplication-tap-highlight" content="no">
<!-- base css -->
<%= stylesheet_link_tag 'application', media: 'all' %><link id="mytheme" rel="stylesheet" media="screen, print" href="#">
<%= stylesheet_link_tag 'smartadmin/skins/skin-master', id: 'myskin', media: 'screen, print' %>

<!-- Place favicon.ico in the root directory -->
<%= render 'shared/favicon' %>

app/views/shared/_inbox_menu.html.erb
<div id="js-inbox-menu" class="flex-wrap position-relative bg-white slide-on-mobile slide-on-mobile-left">
	<div class="position-absolute pos-top pos-bottom w-100">
		<div class="d-flex h-100 flex-column">
			<div class="px-3 px-sm-4 px-lg-5 py-4 align-items-center">

				<div class="btn-group btn-block" role="group" aria-label="Button group with nested dropdown ">
					<button type="button" class="btn btn-danger btn-block fs-md" data-action="toggle" data-class="d-flex" data-target="#panel-compose" data-focus="message-to">Compose</button>
					<div class="btn-group" role="group">
						<button id="btnGroupDrop1" type="button" class="btn btn-danger dropdown-toggle px-2 js-waves-off" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
						<div class="dropdown-menu p-0" aria-labelledby="btnGroupDrop1">
							<a class="dropdown-item" href="#">Work group A</a>
							<a class="dropdown-item" href="#">New page</a>
							<a class="dropdown-item" href="#">Edit signature</a>
							<div class="dropdown-divider m-0"></div>
							<a class="dropdown-item" href="#"> <i class="fas fa-plus width-1"></i> Add more</a>
						</div>
					</div>
				</div>

			</div>

			<div class="flex-1 pr-3">
				<%= link_to page_page_inbox_general_path, class: "dropdown-item px-3 px-sm-4 pr-lg-3 pl-lg-5 py-2 fs-md font-weight-bold d-flex justify-content-between rounded-pill border-top-left-radius-0 border-bottom-left-radius-0 #{'active' if params[:action] == 'page_inbox_general'}" do %>
  <div>
						<i class="fas fa-folder-open width-1"></i>Inbox
					</div>
					<div class="fw-400 fs-xs js-unread-emails-count"></div>
<% end %>
				<a href="javascript:void(0)" class="dropdown-item px-3 px-sm-4 pr-lg-3 pl-lg-5 py-2 fs-md d-flex justify-content-between rounded-pill border-top-left-radius-0 border-bottom-left-radius-0">
					<div>
						<i class="fas fa-star width-1"></i>Starred
					</div>
					<div class="fw-400 fs-xs">(6)</div>
				</a>
				<a href="javascript:void(0)" class="dropdown-item px-3 px-sm-4 pr-lg-3 pl-lg-5 py-2 fs-md d-flex justify-content-between rounded-pill border-top-left-radius-0 border-bottom-left-radius-0">
					<div>
						<i class="fas fa-edit width-1"></i>Draft
					</div>
					<div class="fw-400 fs-xs">(5)</div>
				</a>
				<a href="javascript:void(0)" class="dropdown-item px-3 px-sm-4 pr-lg-3 pl-lg-5 py-2 fs-md d-flex justify-content-between rounded-pill border-top-left-radius-0 border-bottom-left-radius-0">
					<div>
						<i class="fas fa-paper-plane width-1"></i>Sent
					</div>
				</a>
				<a href="javascript:void(0)" class="dropdown-item px-3 px-sm-4 pr-lg-3 pl-lg-5 py-2 fs-md d-flex justify-content-between rounded-pill border-top-left-radius-0 border-bottom-left-radius-0">
					<div>
						<i class="fas fa-exclamation-triangle width-1"></i>Spam
					</div>
				</a>
				<a href="javascript:void(0)" class="dropdown-item px-3 px-sm-4 pr-lg-3 pl-lg-5 py-2 fs-md font-weight-bold d-flex justify-content-between rounded-pill border-top-left-radius-0 border-bottom-left-radius-0">
					<div>
						<i class="fas fa-trash width-1"></i>Trash
					</div>
				</a>

			</div>

			<div class="px-5 py-3 fs-nano fw-500">
				1.5 GB (10%) of 15 GB used
				<div class="progress mt-1" style="height: 7px;">
					<div class="progress-bar" role="progressbar" style="width: 11%;" aria-valuenow="11" aria-valuemin="0" aria-valuemax="100"></div>
				</div>
			</div>

		</div>
	</div>
</div>
<div class="slide-backdrop" data-action="toggle" data-class="slide-on-mobile-left-show" data-target="#js-inbox-menu"></div>

app/views/shared/_nav_footer.html.erb
<div class="nav-footer shadow-top">
	<a href="#" onclick="return false;" data-action="toggle" data-class="nav-function-minify" class="hidden-md-down">
		<i class="ni ni-chevron-right"></i>
		<i class="ni ni-chevron-right"></i>
	</a>
	<ul class="list-table m-auto nav-footer-buttons">
		<li>
			<a href="javascript:void(0);" data-toggle="tooltip" data-placement="top" title="Chat logs">
				<i class="<%= Rails.configuration.icon_prefix %> fa-comments"></i>
			</a>
		</li>
		<li>
			<a href="javascript:void(0);" data-toggle="tooltip" data-placement="top" title="Support Chat">
				<i class="<%= Rails.configuration.icon_prefix %> fa-life-ring"></i>
			</a>
		</li>
		<li>
			<a href="javascript:void(0);" data-toggle="tooltip" data-placement="top" title="Make a call">
				<i class="<%= Rails.configuration.icon_prefix %> fa-phone"></i>
			</a>
		</li>
	</ul>
</div>

app/views/shared/_page_footer.html.erb
<% if Rails.configuration.app_footer %>
<!-- BEGIN Page Footer -->
<footer class="page-footer" role="contentinfo">
	<div class="d-flex align-items-center flex-1 text-muted">
		<span class="hidden-md-down fw-700"><%= Rails.configuration.copyright %></span>
	</div>
	<div>
		<ul class="list-table m-0">
			<li><%= link_to 'About', intel_intel_introduction_path, class: 'text-secondary fw-700' %></li>
			<li class="pl-3"><%= link_to 'License', intel_intel_marketing_dashboard_path, class: 'text-secondary fw-700' %></li>
			<li class="pl-3"><%= link_to 'Documentation', intel_intel_marketing_dashboard_path, class: 'text-secondary fw-700' %></li>
			<li class="pl-3 fs-xl"><a href="https://wrapbootstrap.com/user/MyOrange" class="text-secondary" target="_blank"><i class="<%= Rails.configuration.icon_prefix %> fa-question-circle" aria-hidden="true"></i></a></li>
		</ul>
	</div>
</footer>
<!-- END Page Footer -->
<% end %>